from typing import TYPE_CHECKING, Optional
import anytree

if TYPE_CHECKING:
    from .gates._base_gate import Gate

class GateNode(anytree.Node):
    def __init__(self, gate: Gate, parent_node: "GateNode"): ...
    def add_custom_gate(self, sample_id: str, gate: Gate) -> None: ...
    def is_custom_gate(self, sample_id: str) -> bool: ...
    def get_gate(self, sample_id: Optional[str] = None) -> Gate: ...
